<a href="https://colab.research.google.com/github/Her204/programing/blob/main/Practice-with-plotly.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install cufflinks
!pip install plotly


In [ ]:
import plotly 
import pandas as pd
import cufflinks as cf
from IPython.display import display, HTML

import plotly.io as pio
pio.renderers.default = 'colab'
cf.set_config_file(sharing="public",theme="white",offline=True)
cf.getThemes()

['ggplot', 'pearl', 'solar', 'space', 'white', 'polar', 'henanigans']

In [ ]:
import os
files = os.listdir(os.getcwd())
files = [file for file in files if file.endswith(".csv")]
files

['Metadata_Country_API_SP.POP.TOTL_DS2_es_csv_v2_3012502.csv',
 'API_SP.POP.TOTL_DS2_es_csv_v2_3012502.csv',
 'Metadata_Indicator_API_SP.POP.TOTL_DS2_es_csv_v2_3012502.csv']

In [ ]:
df= pd.read_csv("fao_data_forest_data.csv")

df = df.loc[(df.ELEM==df.ELEM.unique()[1])&(df.GOAL==df.GOAL.unique()[1])]
df = df.sort_values("VALUE",ascending=False)

pivot = df.pivot(columns="YEAR",index="AREA-NEW",values="VALUE")
pivot["TOTAL"] = pivot.sum(axis=1)
pivot = pivot.sort_values("TOTAL",ascending=False)
pivot = pivot.iloc[:6]
pivot

YEAR                         2002.0     2003.0  ...     2007.0      TOTAL
AREA-NEW                                        ...                      
United States of America   989522.0  1204005.0  ...  1107239.0  6407648.0
Turkey                     714517.0   957906.0  ...   716201.0  5214268.0
Brazil                     577089.0   469221.0  ...   756803.0  2620377.0
United Kingdom             567000.0   333300.0  ...   266230.0  2202809.0
France                     539656.0   564047.0  ...        0.0  1932315.0
China                     1100389.0   119597.0  ...     6150.0  1469399.0

[6 rows x 7 columns]

In [13]:
import plotly.offline as py
py.init_notebook_mode(connected=True)
import plotly.graph_objs as go
import plotly.io as pio
pio.renderers.default = 'colab'
from plotly.offline import init_notebook_mode, iplot

In [ ]:
#pivot.iplot(kind="bar")
#pivot.iplot(kind="scatter",mode="markers")
#pivot.iplot(kind="box")
#fp = pivot[pivot.columns[0]].reset_index()
#fp[fp.columns[1]] = fp[fp.columns[1]]/fp[fp.columns[1]].sum()
#fp.iplot(kind="pie",labels=fp.columns[0],values=fp.columns[1])

In [12]:
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import numpy as np
url = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Cat_silhouette.svg/20px-Cat_silhouette.svg.png"
url_2 = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Michis.png/220px-Michis.png"
def rgb2gray(rgb):
    return np.dot(rgb, [0.299, 0.587, 0.144])
img = plt.imread(url_2)
gray = rgb2gray(img)
gray

array([[0.91425099, 0.83641962, 0.69126669, ..., 0.80297648, 0.63636865,
        0.60765884],
       [0.94990981, 0.88306668, 0.65600002, ..., 0.77014119, 0.60930982,
        0.55632159],
       [0.94239608, 0.89631373, 0.66060394, ..., 0.74594904, 0.59376081,
        0.51827454],
       ...,
       [0.4093608 , 0.36036863, 0.41817649, ..., 0.3651451 , 0.39802355,
        0.32879216],
       [0.44523531, 0.40892551, 0.40957649, ..., 0.34147451, 0.33339608,
        0.32935687],
       [0.40319218, 0.34494902, 0.36054118, ..., 0.29130981, 0.31033334,
        0.34955294]])

In [14]:

from scipy import ndimage
gray = rgb2gray(img)
print(gray)
data = go.Heatmap(z=gray/255,colorscale="gray")

fig = go.Figure(data=data)

fig.show()


[[0.91425099 0.83641962 0.69126669 ... 0.80297648 0.63636865 0.60765884]
 [0.94990981 0.88306668 0.65600002 ... 0.77014119 0.60930982 0.55632159]
 [0.94239608 0.89631373 0.66060394 ... 0.74594904 0.59376081 0.51827454]
 ...
 [0.4093608  0.36036863 0.41817649 ... 0.3651451  0.39802355 0.32879216]
 [0.44523531 0.40892551 0.40957649 ... 0.34147451 0.33339608 0.32935687]
 [0.40319218 0.34494902 0.36054118 ... 0.29130981 0.31033334 0.34955294]]
